language: python

python:
    - 2.7

before_install:
    - sudo apt-get update
    - sudo apt-get -y python pip
    - sudo pip install pip --upgrade
    - pip install pep8
    - pip install autopep8

install:
    - pip install -r requirements.txt

script:
    - python hello2.py
    - pytest hello2.py

after-success:
    - travis-after-tesis-success
